version: "3"
services:
  hub:
    image: selenium/hub
  chrome:
    image: selenium/node-chrome   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox
    shm_size: '1gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: azharw49/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result:/usr/share/docker/test-output      
  book-flight-module:
    image: azharw49/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes:
      - ./output/book-result:/usr/share/docker/test-output   